#!/bin/bash

# This script is a convenience script to start the Constellation registry server

createClassPath() {
    basedir=$1
    jar=$2
    classpath="$1/$2"

    if [[ -d ${basedir}/lib ]]
    then
	for i in ${basedir}/lib/*.jar
	do
	    classpath+=":$i"
	done
    fi
}

# READ CONFIG FILE
CONF_FILE="${RAID_DIR}/config.RAID"
CONSTELLATION_PORT="$( cut -d'=' -f2 <<< "$(sed -n '1p' $CONF_FILE)")"
RAID_DIR="$( cut -d'=' -f2 <<< "$(sed -n '2p' $CONF_FILE)")"
RAID_SERVING_PORT="$( cut -d'=' -f2 <<< "$(sed -n '3p' $CONF_FILE)")"
RAID_SERVING_CONFIG="$( cut -d'=' -f2 <<< "$(sed -n '4p' $CONF_FILE)")"

if [[ -z ${CONSTELLATION_PORT} ]] || [[ -z ${RAID_DIR} ]] || [[ -z ${RAID_SERVING_PORT} ]] || [[ -z ${RAID_SERVING_CONFIG} ]]; then
  echo "Config file either missing or corrupted"
  exit 1
fi

BIN_DIR=""

if [[ "${RAID_DIR: -1}" == "/" ]]; then
  BIN_DIR="${RAID_DIR}bin"
else
  BIN_DIR="${RAID_DIR}/bin"
fi

echo ${RAID_DIR}
echo ${BIN_DIR}

source ${BIN_DIR}/create_class_path.bash
CLASSPATH=$(createClassPath ${RAID_DIR} "lib/ipl-support-2.3.1.jar")

exec java -cp ${CLASSPATH} \
     -Dgat.adapter.path \
     -Dibis.io.buffer.size=65536 \
     -Dibis.io.conversion.buffer.size=65536 \
     -Dibis.registry.central.server.connect.timeout=300 \
     -Dlog4j.configuration=file:${RAID_DIR}/log4j.properties \
     -Xmx256M \
     ibis.ipl.server.Server --events --port ${CONSTELLATION_PORT}

